apiVersion: batch/v1
kind: Job
metadata:
  name: annaban-benchmark
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: runner
        image: annaban/benchmark:latest
